apiVersion: v1
kind: pod
metadata:
  name: my-configuration-pod
spec:
  restartPolicy: never
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo \" Configmap environment variable: $CONFIGMAPVAR"]
      env:
      - name: CONFIGMAPVAR
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: key1
      - name: SECRETVAR
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: username
      
      volumeMounts:
      - name: configmap-vol
        mountPath: /etc/configmap
      - name: secret-vol
        mountPath: /etc/secret
        
  volumes:
  - name: configmap-vol
    configMap: 
      name: my-configmap
  - name: secret-vol
    secret:
      name: my-secret