apiVersion: v1
kind: Pod
metadata:
  name: my-probe-pod
spec:
  containers:
  - name: nginx
    image: 1.19.1
    ports:
    - containerPorts: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
      