apiVersion: v1
kind: PersistentVolume
metadata: my-pv
spec:
  storageClassName: localdisk
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
  - path: /tmp/pvoutput
  