apiVersion: v1
kind: Pod
metadata:
  name: my-svc-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.19.1
      ports:
      - containerPort: 80
##########################
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-service
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      