apiVersion: v1
kind: Pod
metatdata:
  name: my-volume-Pod
spec:
  restartPolicy: never
  containers:
  - name: my-volume-pod
    image: busybox
    command: ["sh", "-c", "echo \" Here is output ! \" > /output/output.txt "]
    volumeMounts:
    - name: my-volume
      path: /output
    
volume:
- name: my-volume
  hostPath:
    path: /tmp/output